const fakeData = [
  {
    users: [
      {
        id: 1,
        email: "user1@example.com",
        password: "pass123",
        salt: "salt123",
        createdAt: "2024-01-10T10:00:00Z",
        updatedAt: "2024-10-20T18:30:00Z",
        urls: [
          {
            id: 1,
            url: "https://example.com/longurl1",
            shortUrl: "abc123",
            clickCount: 25,
            createdAt: "2024-02-01T12:30:00Z",
            updatedAt: "2024-10-20T18:30:00Z",
            analytics: [
              {
                id: 1,
                geo: "NORTH_AMERICA",
                referrer: "https://search.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "google",
                utmMedium: "cpc",
                utmCampaign: "summer_sale",
                utmTerm: "shoes",
                utmContent: "banner1",
                createdAt: "2024-02-01T13:00:00Z",
                updatedAt: "2024-02-01T13:00:00Z",
              },
              {
                id: 2,
                geo: "ASIA",
                referrer: "https://social.com",
                userAgent: "Safari/537.36",
                deviceType: "MOBILE",
                utmSource: "facebook",
                utmMedium: "social",
                utmCampaign: "spring_sale",
                utmTerm: "bags",
                utmContent: "post",
                createdAt: "2024-05-06T16:30:00Z",
                updatedAt: "2024-05-06T16:30:00Z",
              },
            ],
          },
          {
            id: 5,
            url: "https://example.com/longurl5",
            shortUrl: "abc345",
            clickCount: 15,
            createdAt: "2024-02-01T12:30:00Z",
            updatedAt: "2024-10-20T18:30:00Z",
            analytics: [
              {
                id: 1,
                geo: "ANTARCTICA",
                referrer: "https://search.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "google",
                utmMedium: "cpc",
                utmCampaign: "summer_sale",
                utmTerm: "shoes",
                utmContent: "banner1",
                createdAt: "2024-02-01T13:00:00Z",
                updatedAt: "2024-02-01T13:00:00Z",
              },
              {
                id: 1,
                geo: "ANTARCTICA",
                referrer: "https://search.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "google",
                utmMedium: "cpc",
                utmCampaign: "summer_sale",
                utmTerm: "shoes",
                utmContent: "banner1",
                createdAt: "2024-02-01T13:00:00Z",
                updatedAt: "2024-02-01T13:00:00Z",
              },
              {
                id: 1,
                geo: "ANTARCTICA",
                referrer: "https://search.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "google",
                utmMedium: "cpc",
                utmCampaign: "summer_sale",
                utmTerm: "shoes",
                utmContent: "banner1",
                createdAt: "2024-02-01T13:00:00Z",
                updatedAt: "2024-02-01T13:00:00Z",
              },
              {
                id: 1,
                geo: "ANTARCTICA",
                referrer: "https://search.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "google",
                utmMedium: "cpc",
                utmCampaign: "summer_sale",
                utmTerm: "shoes",
                utmContent: "banner1",
                createdAt: "2024-02-01T13:00:00Z",
                updatedAt: "2024-02-01T13:00:00Z",
              },
              {
                id: 2,
                geo: "SOUTH_AMERICA",
                referrer: "https://social.com",
                userAgent: "Safari/537.36",
                deviceType: "MOBILE",
                utmSource: "facebook",
                utmMedium: "social",
                utmCampaign: "spring_sale",
                utmTerm: "bags",
                utmContent: "post",
                createdAt: "2024-05-06T16:30:00Z",
                updatedAt: "2024-05-06T16:30:00Z",
              },
            ],
          },
        ],
      },
      {
        id: 2,
        email: "user2@example.com",
        password: "secret456",
        salt: "salt456",
        createdAt: "2024-03-15T15:20:00Z",
        updatedAt: "2024-10-21T09:00:00Z",
        urls: [
          {
            id: 3,
            url: "https://sample.com/yetanotherurl",
            shortUrl: "ghi789",
            clickCount: 10,
            createdAt: "2024-06-10T08:15:00Z",
            updatedAt: "2024-10-21T09:30:00Z",
            analytics: [
              {
                id: 4,
                geo: "OCEANIA",
                referrer: "https://ads.com",
                userAgent: "Mozilla/5.0",
                deviceType: "DESKTOP",
                utmSource: "linkedin",
                utmMedium: "ads",
                utmCampaign: "fall_promo",
                utmTerm: "shirts",
                utmContent: "sidebar",
                createdAt: "2024-08-15T11:00:00Z",
                updatedAt: "2024-08-15T11:00:00Z",
              },
            ],
          },
        ],
      },
    ],
  },
];

export default fakeData
